# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.srcs/sources_1/bd/design_1/ip/design_1_manchester_rs_compos_0_0/design_1_manchester_rs_compos_0_0.xci
# IP: The module: 'design_1_manchester_rs_compos_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: C:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.srcs/sources_1/ip/manchester_rs_composite_ila/manchester_rs_composite_ila.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==manchester_rs_composite_ila || ORIG_REF_NAME==manchester_rs_composite_ila} -quiet] -quiet

# IP: C:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.srcs/sources_1/ip/rs_decoder_sm_1_ila/rs_decoder_sm_1_ila.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rs_decoder_sm_1_ila || ORIG_REF_NAME==rs_decoder_sm_1_ila} -quiet] -quiet

# XDC: c:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.gen/sources_1/ip/manchester_rs_composite_ila/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==manchester_rs_composite_ila || ORIG_REF_NAME==manchester_rs_composite_ila} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.gen/sources_1/ip/manchester_rs_composite_ila/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==manchester_rs_composite_ila || ORIG_REF_NAME==manchester_rs_composite_ila} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.gen/sources_1/ip/manchester_rs_composite_ila/manchester_rs_composite_ila_ooc.xdc

# XDC: c:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.gen/sources_1/ip/rs_decoder_sm_1_ila/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==rs_decoder_sm_1_ila || ORIG_REF_NAME==rs_decoder_sm_1_ila} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.gen/sources_1/ip/rs_decoder_sm_1_ila/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==rs_decoder_sm_1_ila || ORIG_REF_NAME==rs_decoder_sm_1_ila} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.gen/sources_1/ip/rs_decoder_sm_1_ila/rs_decoder_sm_1_ila_ooc.xdc

# IP: C:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.srcs/sources_1/bd/design_1/ip/design_1_manchester_rs_compos_0_0/design_1_manchester_rs_compos_0_0.xci
# IP: The module: 'design_1_manchester_rs_compos_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: C:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.srcs/sources_1/ip/manchester_rs_composite_ila/manchester_rs_composite_ila.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==manchester_rs_composite_ila || ORIG_REF_NAME==manchester_rs_composite_ila} -quiet] -quiet

# IP: C:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.srcs/sources_1/ip/rs_decoder_sm_1_ila/rs_decoder_sm_1_ila.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rs_decoder_sm_1_ila || ORIG_REF_NAME==rs_decoder_sm_1_ila} -quiet] -quiet

# XDC: c:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.gen/sources_1/ip/manchester_rs_composite_ila/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==manchester_rs_composite_ila || ORIG_REF_NAME==manchester_rs_composite_ila} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.gen/sources_1/ip/manchester_rs_composite_ila/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==manchester_rs_composite_ila || ORIG_REF_NAME==manchester_rs_composite_ila} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.gen/sources_1/ip/manchester_rs_composite_ila/manchester_rs_composite_ila_ooc.xdc

# XDC: c:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.gen/sources_1/ip/rs_decoder_sm_1_ila/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==rs_decoder_sm_1_ila || ORIG_REF_NAME==rs_decoder_sm_1_ila} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.gen/sources_1/ip/rs_decoder_sm_1_ila/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==rs_decoder_sm_1_ila || ORIG_REF_NAME==rs_decoder_sm_1_ila} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.gen/sources_1/ip/rs_decoder_sm_1_ila/rs_decoder_sm_1_ila_ooc.xdc
