# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.srcs/sources_1/bd/design_1/ip/design_1_agc_cdr_sm_3_1_0/design_1_agc_cdr_sm_3_1_0.xci
# IP: The module: 'design_1_agc_cdr_sm_3_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: C:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.srcs/sources_1/ip/agc_cdr_sm_3_composite_ila/agc_cdr_sm_3_composite_ila.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==agc_cdr_sm_3_composite_ila || ORIG_REF_NAME==agc_cdr_sm_3_composite_ila} -quiet] -quiet

# IP: C:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.srcs/sources_1/ip/cdr_sm_ila_2/cdr_sm_ila_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cdr_sm_ila_2 || ORIG_REF_NAME==cdr_sm_ila_2} -quiet] -quiet

# IP: C:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.srcs/sources_1/ip/freq_err_mult_gen/freq_err_mult_gen.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==freq_err_mult_gen || ORIG_REF_NAME==freq_err_mult_gen} -quiet] -quiet

# IP: C:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.srcs/sources_1/ip/i_q_channel_mult_gen/i_q_channel_mult_gen.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==i_q_channel_mult_gen || ORIG_REF_NAME==i_q_channel_mult_gen} -quiet] -quiet

# IP: C:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.srcs/sources_1/ip/freq_err_fir_1/freq_err_fir_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==freq_err_fir_1 || ORIG_REF_NAME==freq_err_fir_1} -quiet] -quiet

# IP: C:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.srcs/sources_1/ip/cdr_dds_compiler/cdr_dds_compiler.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cdr_dds_compiler || ORIG_REF_NAME==cdr_dds_compiler} -quiet] -quiet

# IP: C:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.srcs/sources_1/ip/agc_ila_2/agc_ila_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==agc_ila_2 || ORIG_REF_NAME==agc_ila_2} -quiet] -quiet

# IP: C:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.srcs/sources_1/ip/agc_div_gen/agc_div_gen.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==agc_div_gen || ORIG_REF_NAME==agc_div_gen} -quiet] -quiet

# XDC: c:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.gen/sources_1/ip/agc_cdr_sm_3_composite_ila/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==agc_cdr_sm_3_composite_ila || ORIG_REF_NAME==agc_cdr_sm_3_composite_ila} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.gen/sources_1/ip/agc_cdr_sm_3_composite_ila/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==agc_cdr_sm_3_composite_ila || ORIG_REF_NAME==agc_cdr_sm_3_composite_ila} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.gen/sources_1/ip/agc_cdr_sm_3_composite_ila/agc_cdr_sm_3_composite_ila_ooc.xdc

# XDC: c:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.gen/sources_1/ip/cdr_sm_ila_2/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==cdr_sm_ila_2 || ORIG_REF_NAME==cdr_sm_ila_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.gen/sources_1/ip/cdr_sm_ila_2/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==cdr_sm_ila_2 || ORIG_REF_NAME==cdr_sm_ila_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.gen/sources_1/ip/cdr_sm_ila_2/cdr_sm_ila_2_ooc.xdc

# XDC: c:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.gen/sources_1/ip/freq_err_fir_1/constraints/fir_compiler_v7_2.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==freq_err_fir_1 || ORIG_REF_NAME==freq_err_fir_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.gen/sources_1/ip/agc_ila_2/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==agc_ila_2 || ORIG_REF_NAME==agc_ila_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.gen/sources_1/ip/agc_ila_2/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==agc_ila_2 || ORIG_REF_NAME==agc_ila_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.gen/sources_1/ip/agc_ila_2/agc_ila_2_ooc.xdc

# IP: C:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.srcs/sources_1/bd/design_1/ip/design_1_agc_cdr_sm_3_1_0/design_1_agc_cdr_sm_3_1_0.xci
# IP: The module: 'design_1_agc_cdr_sm_3_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: C:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.srcs/sources_1/ip/agc_cdr_sm_3_composite_ila/agc_cdr_sm_3_composite_ila.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==agc_cdr_sm_3_composite_ila || ORIG_REF_NAME==agc_cdr_sm_3_composite_ila} -quiet] -quiet

# IP: C:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.srcs/sources_1/ip/cdr_sm_ila_2/cdr_sm_ila_2.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cdr_sm_ila_2 || ORIG_REF_NAME==cdr_sm_ila_2} -quiet] -quiet

# IP: C:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.srcs/sources_1/ip/freq_err_mult_gen/freq_err_mult_gen.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==freq_err_mult_gen || ORIG_REF_NAME==freq_err_mult_gen} -quiet] -quiet

# IP: C:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.srcs/sources_1/ip/i_q_channel_mult_gen/i_q_channel_mult_gen.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==i_q_channel_mult_gen || ORIG_REF_NAME==i_q_channel_mult_gen} -quiet] -quiet

# IP: C:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.srcs/sources_1/ip/freq_err_fir_1/freq_err_fir_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==freq_err_fir_1 || ORIG_REF_NAME==freq_err_fir_1} -quiet] -quiet

# IP: C:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.srcs/sources_1/ip/cdr_dds_compiler/cdr_dds_compiler.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cdr_dds_compiler || ORIG_REF_NAME==cdr_dds_compiler} -quiet] -quiet

# IP: C:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.srcs/sources_1/ip/agc_ila_2/agc_ila_2.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==agc_ila_2 || ORIG_REF_NAME==agc_ila_2} -quiet] -quiet

# IP: C:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.srcs/sources_1/ip/agc_div_gen/agc_div_gen.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==agc_div_gen || ORIG_REF_NAME==agc_div_gen} -quiet] -quiet

# XDC: c:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.gen/sources_1/ip/agc_cdr_sm_3_composite_ila/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==agc_cdr_sm_3_composite_ila || ORIG_REF_NAME==agc_cdr_sm_3_composite_ila} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.gen/sources_1/ip/agc_cdr_sm_3_composite_ila/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==agc_cdr_sm_3_composite_ila || ORIG_REF_NAME==agc_cdr_sm_3_composite_ila} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.gen/sources_1/ip/agc_cdr_sm_3_composite_ila/agc_cdr_sm_3_composite_ila_ooc.xdc

# XDC: c:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.gen/sources_1/ip/cdr_sm_ila_2/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==cdr_sm_ila_2 || ORIG_REF_NAME==cdr_sm_ila_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.gen/sources_1/ip/cdr_sm_ila_2/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==cdr_sm_ila_2 || ORIG_REF_NAME==cdr_sm_ila_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.gen/sources_1/ip/cdr_sm_ila_2/cdr_sm_ila_2_ooc.xdc

# XDC: c:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.gen/sources_1/ip/freq_err_fir_1/constraints/fir_compiler_v7_2.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==freq_err_fir_1 || ORIG_REF_NAME==freq_err_fir_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.gen/sources_1/ip/agc_ila_2/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==agc_ila_2 || ORIG_REF_NAME==agc_ila_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.gen/sources_1/ip/agc_ila_2/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==agc_ila_2 || ORIG_REF_NAME==agc_ila_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.gen/sources_1/ip/agc_ila_2/agc_ila_2_ooc.xdc
