# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/cmod_a7_phys_const.xdc

# IP: ip/manchester_rs_composite_ila/manchester_rs_composite_ila.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==manchester_rs_composite_ila || ORIG_REF_NAME==manchester_rs_composite_ila} -quiet] -quiet

# IP: ip/rs_decoder_sm_1_ila/rs_decoder_sm_1_ila.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rs_decoder_sm_1_ila || ORIG_REF_NAME==rs_decoder_sm_1_ila} -quiet] -quiet

# IP: ip/agc_cdr_sm_3_composite_ila/agc_cdr_sm_3_composite_ila.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==agc_cdr_sm_3_composite_ila || ORIG_REF_NAME==agc_cdr_sm_3_composite_ila} -quiet] -quiet

# IP: ip/cdr_sm_ila_2/cdr_sm_ila_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cdr_sm_ila_2 || ORIG_REF_NAME==cdr_sm_ila_2} -quiet] -quiet

# IP: ip/freq_err_mult_gen/freq_err_mult_gen.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==freq_err_mult_gen || ORIG_REF_NAME==freq_err_mult_gen} -quiet] -quiet

# IP: ip/i_q_channel_mult_gen/i_q_channel_mult_gen.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==i_q_channel_mult_gen || ORIG_REF_NAME==i_q_channel_mult_gen} -quiet] -quiet

# IP: ip/freq_err_fir_1/freq_err_fir_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==freq_err_fir_1 || ORIG_REF_NAME==freq_err_fir_1} -quiet] -quiet

# IP: ip/cdr_dds_compiler/cdr_dds_compiler.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cdr_dds_compiler || ORIG_REF_NAME==cdr_dds_compiler} -quiet] -quiet

# IP: ip/agc_ila_2/agc_ila_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==agc_ila_2 || ORIG_REF_NAME==agc_ila_2} -quiet] -quiet

# IP: ip/agc_div_gen/agc_div_gen.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==agc_div_gen || ORIG_REF_NAME==agc_div_gen} -quiet] -quiet

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xadc_wiz_0_0/design_1_xadc_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xadc_wiz_0_0 || ORIG_REF_NAME==design_1_xadc_wiz_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_0/design_1_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_0 || ORIG_REF_NAME==design_1_xlconstant_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_0_0/design_1_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_0 || ORIG_REF_NAME==design_1_xlslice_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_1/design_1_clk_wiz_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_1 || ORIG_REF_NAME==design_1_clk_wiz_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_consts_0_0/design_1_axi_gpio_consts_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_consts_0_0 || ORIG_REF_NAME==design_1_axi_gpio_consts_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_manchester_rs_compos_0_0/design_1_manchester_rs_compos_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_manchester_rs_compos_0_0 || ORIG_REF_NAME==design_1_manchester_rs_compos_0_0} -quiet] -quiet

# IP: ip/manchester_rs_composite_ila/manchester_rs_composite_ila.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==manchester_rs_composite_ila || ORIG_REF_NAME==manchester_rs_composite_ila} -quiet] -quiet

# IP: ip/rs_decoder_sm_1_ila/rs_decoder_sm_1_ila.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rs_decoder_sm_1_ila || ORIG_REF_NAME==rs_decoder_sm_1_ila} -quiet] -quiet

# IP: bd/design_1/ip/design_1_agc_cdr_sm_3_1_0/design_1_agc_cdr_sm_3_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_agc_cdr_sm_3_1_0 || ORIG_REF_NAME==design_1_agc_cdr_sm_3_1_0} -quiet] -quiet

# IP: ip/agc_cdr_sm_3_composite_ila/agc_cdr_sm_3_composite_ila.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==agc_cdr_sm_3_composite_ila || ORIG_REF_NAME==agc_cdr_sm_3_composite_ila} -quiet] -quiet

# IP: ip/cdr_sm_ila_2/cdr_sm_ila_2.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cdr_sm_ila_2 || ORIG_REF_NAME==cdr_sm_ila_2} -quiet] -quiet

# IP: ip/freq_err_mult_gen/freq_err_mult_gen.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==freq_err_mult_gen || ORIG_REF_NAME==freq_err_mult_gen} -quiet] -quiet

# IP: ip/i_q_channel_mult_gen/i_q_channel_mult_gen.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==i_q_channel_mult_gen || ORIG_REF_NAME==i_q_channel_mult_gen} -quiet] -quiet

# IP: ip/freq_err_fir_1/freq_err_fir_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==freq_err_fir_1 || ORIG_REF_NAME==freq_err_fir_1} -quiet] -quiet

# IP: ip/cdr_dds_compiler/cdr_dds_compiler.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cdr_dds_compiler || ORIG_REF_NAME==cdr_dds_compiler} -quiet] -quiet

# IP: ip/agc_ila_2/agc_ila_2.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==agc_ila_2 || ORIG_REF_NAME==agc_ila_2} -quiet] -quiet

# IP: ip/agc_div_gen/agc_div_gen.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==agc_div_gen || ORIG_REF_NAME==agc_div_gen} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rs_decoder_init_rst_0_0/design_1_rs_decoder_init_rst_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_rs_decoder_init_rst_0_0 || ORIG_REF_NAME==design_1_rs_decoder_init_rst_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_msg_detected_led_1_0_0/design_1_msg_detected_led_1_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_msg_detected_led_1_0_0 || ORIG_REF_NAME==design_1_msg_detected_led_1_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_microblaze_0_0/design_1_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_microblaze_0_0 || ORIG_REF_NAME==design_1_microblaze_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_dlmb_v10_0/design_1_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_dlmb_v10_0 || ORIG_REF_NAME==design_1_dlmb_v10_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ilmb_v10_0/design_1_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ilmb_v10_0 || ORIG_REF_NAME==design_1_ilmb_v10_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_dlmb_bram_if_cntlr_0/design_1_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==design_1_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ilmb_bram_if_cntlr_0/design_1_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==design_1_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_lmb_bram_0/design_1_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_lmb_bram_0 || ORIG_REF_NAME==design_1_lmb_bram_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_0/design_1_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xbar_0 || ORIG_REF_NAME==design_1_xbar_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_microblaze_0_axi_periph_0/design_1_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_microblaze_0_axi_periph_0 || ORIG_REF_NAME==design_1_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_microblaze_0_axi_intc_0/design_1_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_microblaze_0_axi_intc_0 || ORIG_REF_NAME==design_1_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_microblaze_0_xlconcat_0/design_1_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_microblaze_0_xlconcat_0 || ORIG_REF_NAME==design_1_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mdm_1_0/design_1_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_mdm_1_0 || ORIG_REF_NAME==design_1_mdm_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_clk_wiz_156M_0/design_1_rst_clk_wiz_156M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_rst_clk_wiz_156M_0 || ORIG_REF_NAME==design_1_rst_clk_wiz_156M_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_0_0 || ORIG_REF_NAME==design_1_axi_gpio_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_0_1/design_1_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_0_1 || ORIG_REF_NAME==design_1_axi_gpio_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_1_0/design_1_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_1_0 || ORIG_REF_NAME==design_1_axi_gpio_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_1_1/design_1_axi_gpio_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_1_1 || ORIG_REF_NAME==design_1_axi_gpio_1_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_4_0/design_1_axi_gpio_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_4_0 || ORIG_REF_NAME==design_1_axi_gpio_4_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_5_0/design_1_axi_gpio_5_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_5_0 || ORIG_REF_NAME==design_1_axi_gpio_5_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_6_0/design_1_axi_gpio_6_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_6_0 || ORIG_REF_NAME==design_1_axi_gpio_6_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_decoded_data_mem_map_0_3/design_1_decoded_data_mem_map_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_decoded_data_mem_map_0_3 || ORIG_REF_NAME==design_1_decoded_data_mem_map_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_7_0/design_1_axi_gpio_7_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_7_0 || ORIG_REF_NAME==design_1_axi_gpio_7_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_uartlite_0_0/design_1_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_uartlite_0_0 || ORIG_REF_NAME==design_1_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mux_select_1_0_0/design_1_mux_select_1_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_mux_select_1_0_0 || ORIG_REF_NAME==design_1_mux_select_1_0_0} -quiet] -quiet

# XDC: c:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.gen/sources_1/ip/manchester_rs_composite_ila/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==manchester_rs_composite_ila || ORIG_REF_NAME==manchester_rs_composite_ila} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.gen/sources_1/ip/manchester_rs_composite_ila/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==manchester_rs_composite_ila || ORIG_REF_NAME==manchester_rs_composite_ila} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.gen/sources_1/ip/manchester_rs_composite_ila/manchester_rs_composite_ila_ooc.xdc

# XDC: c:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.gen/sources_1/ip/rs_decoder_sm_1_ila/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==rs_decoder_sm_1_ila || ORIG_REF_NAME==rs_decoder_sm_1_ila} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.gen/sources_1/ip/rs_decoder_sm_1_ila/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==rs_decoder_sm_1_ila || ORIG_REF_NAME==rs_decoder_sm_1_ila} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.gen/sources_1/ip/rs_decoder_sm_1_ila/rs_decoder_sm_1_ila_ooc.xdc

# XDC: c:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.gen/sources_1/ip/agc_cdr_sm_3_composite_ila/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==agc_cdr_sm_3_composite_ila || ORIG_REF_NAME==agc_cdr_sm_3_composite_ila} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.gen/sources_1/ip/agc_cdr_sm_3_composite_ila/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==agc_cdr_sm_3_composite_ila || ORIG_REF_NAME==agc_cdr_sm_3_composite_ila} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.gen/sources_1/ip/agc_cdr_sm_3_composite_ila/agc_cdr_sm_3_composite_ila_ooc.xdc

# XDC: c:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.gen/sources_1/ip/cdr_sm_ila_2/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==cdr_sm_ila_2 || ORIG_REF_NAME==cdr_sm_ila_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.gen/sources_1/ip/cdr_sm_ila_2/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==cdr_sm_ila_2 || ORIG_REF_NAME==cdr_sm_ila_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.gen/sources_1/ip/cdr_sm_ila_2/cdr_sm_ila_2_ooc.xdc

# XDC: c:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.gen/sources_1/ip/freq_err_fir_1/constraints/fir_compiler_v7_2.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==freq_err_fir_1 || ORIG_REF_NAME==freq_err_fir_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.gen/sources_1/ip/agc_ila_2/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==agc_ila_2 || ORIG_REF_NAME==agc_ila_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.gen/sources_1/ip/agc_ila_2/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==agc_ila_2 || ORIG_REF_NAME==agc_ila_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.gen/sources_1/ip/agc_ila_2/agc_ila_2_ooc.xdc

# XDC: c:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.gen/sources_1/ip/manchester_rs_composite_ila/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==manchester_rs_composite_ila || ORIG_REF_NAME==manchester_rs_composite_ila} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.gen/sources_1/ip/manchester_rs_composite_ila/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==manchester_rs_composite_ila || ORIG_REF_NAME==manchester_rs_composite_ila} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.gen/sources_1/ip/manchester_rs_composite_ila/manchester_rs_composite_ila_ooc.xdc

# XDC: c:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.gen/sources_1/ip/rs_decoder_sm_1_ila/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==rs_decoder_sm_1_ila || ORIG_REF_NAME==rs_decoder_sm_1_ila} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.gen/sources_1/ip/rs_decoder_sm_1_ila/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==rs_decoder_sm_1_ila || ORIG_REF_NAME==rs_decoder_sm_1_ila} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.gen/sources_1/ip/rs_decoder_sm_1_ila/rs_decoder_sm_1_ila_ooc.xdc

# XDC: c:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.gen/sources_1/ip/agc_cdr_sm_3_composite_ila/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==agc_cdr_sm_3_composite_ila || ORIG_REF_NAME==agc_cdr_sm_3_composite_ila} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.gen/sources_1/ip/agc_cdr_sm_3_composite_ila/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==agc_cdr_sm_3_composite_ila || ORIG_REF_NAME==agc_cdr_sm_3_composite_ila} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.gen/sources_1/ip/agc_cdr_sm_3_composite_ila/agc_cdr_sm_3_composite_ila_ooc.xdc

# XDC: c:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.gen/sources_1/ip/cdr_sm_ila_2/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==cdr_sm_ila_2 || ORIG_REF_NAME==cdr_sm_ila_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.gen/sources_1/ip/cdr_sm_ila_2/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==cdr_sm_ila_2 || ORIG_REF_NAME==cdr_sm_ila_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.gen/sources_1/ip/cdr_sm_ila_2/cdr_sm_ila_2_ooc.xdc

# XDC: c:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.gen/sources_1/ip/freq_err_fir_1/constraints/fir_compiler_v7_2.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==freq_err_fir_1 || ORIG_REF_NAME==freq_err_fir_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.gen/sources_1/ip/agc_ila_2/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==agc_ila_2 || ORIG_REF_NAME==agc_ila_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.gen/sources_1/ip/agc_ila_2/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==agc_ila_2 || ORIG_REF_NAME==agc_ila_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.gen/sources_1/ip/agc_ila_2/agc_ila_2_ooc.xdc

# XDC: c:/Xilinx2023_workspace/vivado_workspace/cmod_4/cmod_4/cmod_4.gen/sources_1/bd/design_1/design_1_ooc.xdc
